396 update anvil catalog entity list config
clevercanary/data-browser pull request #399
Opened 2022-08-05 22:06 UTC by jpaten

### Ticket
Closes #396.

### Reviewers
@MillenniumFalconMechanic .

### Changes
- Separated viewbuilders & transformers and moved to correct folders as specified by the configuration guide
- Moved `anvil-catalog` & `anvil` model builders to correct folders as specified by the configuration guide
- 

### Definition of Done (from ticket)
  - Workspace entity config is updated to match 
  - anvil-catalog-specific view builders file created.
  - anvil-catalog-specific transformers file created (with the existing workspaceTransformer.ts removed).

### QA steps (optional)

### Known Issues
- Kept currently unused `anvil-catalog` model builder

2022-08-05 23:35 UTC, MillenniumFalconMechanic commented on LICENSE
> +      other workspaceEntityConfig that control, are controlled by, or are under common
Looks like you did a rename that went a little wide! :) Would you be able to revert this change?

2022-08-05 23:36 UTC, MillenniumFalconMechanic commented on docs/configuration-guide.md
Same as above!

2022-08-05 23:40 UTC, MillenniumFalconMechanic commented on explorer/app/apis/azul/common/entities.ts
>  import { CategoryKey, CategoryValueKey } from "../../../common/entities";
Revert renaming!

2022-08-06 06:11 UTC, jpaten commented
Looks like I might also have not separated the model builders and transformers properly. In this configuration it appears that the model builders add text formatting, but based on the guide and the hca-dcp implementation (#401) that should probably happen in the transformers. Let me know which way around is right(or if it doesn't matter) and I'll change if necessary!

2022-08-07 02:24 UTC, jpaten commented
Wait nvm think I misunderstood disregard the prior comment

2022-08-08 16:12 UTC, MillenniumFalconMechanic commented on docs/configuration-guide.md
> +* Naming convention: `entities.ts`.
Thank you!

2022-08-08 16:18 UTC, MillenniumFalconMechanic commented on explorer/app/viewModelBuilders/anvil-catalog/common/viewModelBuilders.ts
> +): React.ComponentProps<typeof C.Text> => createColumn(getStudyName(source));
Replace usage of `Text` with `Cell`, here and throughout (and also in the view model builder). Ideally we'd just call `ViewModelBuilder.getStudyName()` here (and we can then also remove the `createColumn` function above).

2022-08-08 16:21 UTC, MillenniumFalconMechanic commented on explorer/app/apis/anvil-catalog/common/transformers.ts
> +export const getStudyName = (source: AnvilSourceItem): string => source?.name;
I think we can remove the optional chaining (`source?`) as the `source` param isn't optional.

Would you mind adding nullish coalescing (returning "") to each function here in the transformer so the transformer functions always return a string value (and not undefined or null).

2022-08-08 16:23 UTC, MillenniumFalconMechanic requested changes
Looking good Jonah, thank you! I have a couple of small nits for you to take a look at when you have a moment.

2022-08-09 07:26 UTC, closed without merging